### ISSUE TITLE
[Rust] Can't get minimal example to run

### ISSUE THREAD

**Issue by Freymaurer** [fable-compiler/Fable#3637]
### Description

I should start with i have never done anything with/in rust before.

Here is what i did trying to setup fable-rust.

1. Install [DOWNLOAD RUSTUP-INIT.EXE (64-BIT](https://www.rust-lang.org/learn/get-started)
2. create new folder
3. `dotnet new tool-manifest`
4. `dotnet install fable`
5. create `Cargo.toml` (See Repro code)
6. create `test.fsx` (See Repro code)
7. run `dotnet fable test.fsx --lang rust -e rs --noCache`, creating `test.rs`.
8. `cargo clean`
9. `cargo build`

get the following error:
![image](https://github.com/fable-compiler/Fable/assets/39732517/36419a9f-6e4b-47fd-8e82-136d94eb4dce)

### Repro code

```fsharp
//test.fsx
#r "nuget: Fable.Core, 4.2.0"

[<EntryPoint>]
let main argv =
  printfn "Hello World!"
  0
```

```toml
[package]
name = "fable-rust-sample"
version = "0.1.0"
edition = "2021" 

[[bin]]
name = "test"
path = "test.rs"

[dependencies]
fable_library_rust = { path = "./fable_modules/fable-library-rust" }
```

Copying the code from `test.fsx` into fable repl does not print `"Hello World!"` either.

### Expected and actual results

I would expect `"Hello World!"` console output.

### Related information

* Fable version: `4.6.0`
* Operating system: Windows 11
